# Generated by Django 4.0.1 on 2022-01-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('id', models.AutoField(help_text='id主键', primary_key=True, serialize=False, verbose_name='id主键')),
                ('name', models.CharField(help_text='项目名称', max_length=200, unique=True, verbose_name='项目名称')),
                ('leader', models.CharField(help_text='项目负责人', max_length=50, verbose_name='负责人')),
                ('desc', models.CharField(blank=True, default='', help_text='简要描述', max_length=200, null=True, verbose_name='简要描述')),
            ],
            options={
                'verbose_name': '项目信息',
                'db_table': 'projects_info',
            },
        ),
    ]
