# Generated by Django 4.0.1 on 2022-02-01 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': '项目信息', 'verbose_name_plural': '项目信息'},
        ),
    ]
