# Generated by Django 4.1.3 on 2022-12-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_alter_dept_options_dept_email_dept_owner_dept_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dept',
            name='desc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='描述'),
        ),
    ]
