# Generated by Django 4.1.3 on 2022-12-05 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_dept_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dept',
            name='type',
        ),
    ]
