# Generated by Django 4.1.3 on 2022-12-06 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_remove_dept_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dept',
            name='pid',
        ),
        migrations.AddField(
            model_name='dept',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.dept', verbose_name='上级部门'),
        ),
    ]
