# Generated by Django 4.1.3 on 2022-12-07 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0007_dept_child'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dept',
            old_name='child',
            new_name='children',
        ),
    ]
