# Generated by Django 4.1.3 on 2022-12-07 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0009_remove_dept_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdept', to='rbac.dept', verbose_name='上级部门'),
        ),
    ]
