# Generated by Django 4.0.2 on 2022-02-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('userId', models.CharField(help_text='用户ID', max_length=10, primary_key=True, serialize=False, verbose_name='用户ID')),
                ('userName', models.CharField(help_text='用户名称', max_length=200, verbose_name='用户名称')),
                ('roleId', models.CharField(help_text='角色ID', max_length=10, verbose_name='角色ID')),
                ('menu', models.TextField(help_text='菜单明细', verbose_name='菜单明细')),
            ],
            options={
                'verbose_name': '菜单信息',
                'verbose_name_plural': '菜单信息',
                'db_table': 'menu_info',
            },
        ),
    ]
